apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: fluxcdtutorial
  labels:
    name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
    - port: 443
      nodePort: 30443
      name: https
  selector:
    app: nginxpod