apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: fluxcdtutorial
spec:
  encryptedData:
    password: AgCGXXUhb4QnP0uP+kmOSuSKf9g26WwAYU91pd6tg1Z3v4Txe1kdYnDlueHty6L0/BRl1FxkgFe3w7s1fSmpNEwmjcwh2hCjFfItgMQdCLYtCzRJejGs6hB54k/pFYKTuYP8v7CCCAHZVVaqMBu36nuc/oq4wQItOM6iS0hy6p8IPU0dKnsj2QAMAOpMWDx0Ss9X8/Ps4g2/pOL7M54DYT9dZb/FXucqMTy8kXXEAQozLt+MD+x+UT8g27lW9msnTkb+Q57KAbkfDhkb4V+mnHfugoEhPxWkwIlvJPkm7vRH0aIDFUjzqv6MrALpeEIpW99yu9oXLpRdsR5Sg+/i+lF69o8wRK86ueNaxVgHicY64yJVpJ/nrXbbKesQpJGP6hzqXtiTqY5rkF376WMGLCRFB2lfRQQ55t69Aq7WJdyOozHfVULN+mOEPzwf6eGdyyuIxFLVh6tq9U2JI2IehW7cFTw8ygIV1rxRgMlFyT53r2yZq1+OMEeHI1SupC8i/3VCAQlQuvyiSHTezZn9VGgJSC+QSn+FKtZ5yMip7rpOYlzziNyWxYwrfO9BugNTVNUfEGyOEqrjYSvjqbsLtJP7zC1/MLNeiJ/HXSqeOR5Axtb/aJHuikqZVGYqxQB4VHkVrLWcn9klAFLQvECMiEshl2fvhupavcZ2mFQEqEFqXGXuI2zcUcmWoof/OLLhpUZkmUDl6kni/w==
    username: AgBWiZkiDLKXZIVEzEc6ZNBkqHcl6lOh23q1IiG8Afwesi4C3BvmZpcIsJq//vJydU00MogW4yqAyh1cOceHFkXRh3vAAeNMa/nNc3wbl2YNlyS/jUXvcsoAMnNssPpwMxOSVDtTZuaaKcgBWT7rPVDqlEL2rpOVXtYJf3HLRe7Ooujlu+Xp90UugV24hpc8Xi4dDmqyjkOa9ad0t2gGGpK3maweMbq//5PilbY6FXXUGSDte8zHA7eCQgHDQc3SBZtXpFHQjE13KGGxaNtOT+B9221Dy7IH2lupRTluSpwQDeu4i5bk3BvXfbP6gqDj3oRv59ykLfUaey9b3cYeo4T5W3qRb6glJmj+epB3UHj7RuJ84mWUYOEYVTREO925WORn5dXsa/KXeL1YwKsVXomUkNiOM5mFiQM+QgKloKvATU0+h9Xi/GPtHjq+oGBTQrIEsTfmbDJ2VTukKLOxs8Dln7pG+LpA0DQNI6B/BbjBvIAruVJN8Az0WGoq043uG5N5TQUuawGXtufQE12PwSWvpVFbN8VkCI0CWeQjCX0j9YuhCBaj18haY6cITDyVKwxgkZw7os21x8ggj5SE9Lh7ik0x3rWSqifY+BTelEjx5OyMNVQrqaLEPHIQ5GPEoBXf1HJwxV1Vs7haQZQOn94CbrX0xOVVmHczCDn0Mus/yna7eCZ11liesgaAU8/3B0EirgPju/3nXw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: fluxcdtutorial

