apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: fluxcdtutorial
data:
  password: dXNlcm5hbWU=        # base64 encoded username
  username: cGFzc3dvcmQ=        # base64 encoded password


  