apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: deploymentstatus
  namespace: fluxcdtutorial
spec:
  providerRef:
    name: githubprovider
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: k8snginxappsotkust
      namespace: fluxcdtutorial