apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: fluxcdtutorial
spec:
  encryptedData:
    token: AgClA+qFHcKsUpfX4l57sBa4StpCsfKilaAGWxp6uE8yyE0g7aLDuOQBgUJNnGMEhT7T3fOJSvpLzown+8JRj6E+WQcx1dDryUfNFcclk7SgILP4TXTT+L46SWJzesVqehEy4ZRMmHcF9kw6kQIXjqnkdsQfU/p7InfPXYi4bvV7eXVFd2DyoRxeMLy+VzSa7CGL9VJYAJ/vNvIhhciESDCpcAaFK6z5YqSCZsyPkoN9DpiDkRXUkBdUiJKdNX0WP1XHrPytyFqi1L1cv1c/aob5CDeC7Mp1CNPUkaR319Dm3W95NgHMB1sQvR4fPsy82HL8O/NM3DmLhaYeBFKL0RdkiyHv+PR8W90BZYDEOgOwTpl5ovMFwPUXXQZIFMomht4oLq3xERWEDOu7yN4ID98jtlW0Shc335S0+o46/2XXAL+H35HsFE8+ZEaPKAH6+fQBRPFk+Z18om1xox8bLS2lJvaRNrllP8fiYQ/F/YQgftrVIZfw5qcu8ONz/qJjjzQUSTWxTy7mMSHnD5A/kNOiyx8hOgf6iWqo7fyZRhKBiSFs2yjeSnDCjB19tx8ipU9OoV5S+zNnjt1RRIMcqREG+/WUdySl0wEdW/aZaN+9qgnKiCKul/9u5n+F+Hh3n02wiImjWcFpcNqos+g1Nx7t8uDQxwO3TVStODKDhlaIh21b/1+2u/No0NuBANbus5JfsgAncmgO/WZGqhrPIUdCBdSfkispEbYzBCRLh5qEbkL/3CPsV/co
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github
      namespace: fluxcdtutorial

