apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: fluxcdtutorial
spec:
  encryptedData:
    token: AgAW7NWwuBepAz1GMyEWTlfrji1xE27aizhN6hdm4vbsnnM4P5u95FyOlp0j11NL5aU7pkxaAPJzgbYYf9qPGF6ij2nz5z+/999XCVrhJwH1ljarVZaXO2MQ/OxivqhcLnB4IYaNxGtRiLAXSQsw+a4dA7SA8YkeohO8Qnm/aWd77m/ox60Vg00R3ufIX78X/K6Aygm8VscDK8yParEUtO6cq7x86Iy7rOwkbVBB0bLc9mOi/VkPOerK3efqnZzvDhJN2hvRG57ZwtY9KpTHNdLmgJVmoEAAeYAkffnj+nEODER/0hG1ePcLuvZ/zbHvF/UKqvbGr723he/EndT6xQgXsNmYvgVEDOk659DrnXvnx0+WNmSGGrFztkA51xOlVBv5d5HmnJMgisVUag1cYXUFWvoupVRIw55G/ME+nF8lq/c49U75LzTZ6/ItU1pjcReK512pPqCUwwmiJ2L7cY9gqsHExHf6pN1htHqL+Fz+eKF4Lx9dDK1iGrO1M4hm4o2bj9si+9yT75lpQW4HZD7Mke7tK5TrGYmMjEIE/PnE8Yg29WhyMOVfGdS5gUx9bl5VzpGwTiti6TzZ3Pi2YtcvamozGd3hLjWy3o9DJynxBlqtlV8XDn6jql1qB5kzO9Sr+h2ex8SOdp9NBgScx/w6FCIagvthAtjChQWSvRW9Kmcvi3F/I4765vqnIt9NWqYITB5i8g/kfsc0NpzlFzZi9sMcrDKTn/2P+OD07HmqT2SMStqjSPsazA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github
      namespace: fluxcdtutorial

